name: sorokchat
services:
  sorokchat.server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sorokchat.server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - sorokchat.database
  sorokchat.pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sorokchat.pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: Sorokovskys@ukr.net
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  sorokchat.database:
    image: postgres:18-alpine
    container_name: sorokchat.database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sorokchat
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
  pgadmin_data: 