spring:
  application:
    name: sorokchat
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/sorokchat
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    urls:
      - name: API
        url: /openapi.yaml
    disable-swagger-default-url: true